version: '3.7'

services:

  db:
    environment:
      POSTGRES_DB: db
      POSTGRES_INITDB_ARGS: "--encoding=UTF8"
    image: postgres:9.6-alpine
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data

  web:
    build: 
      context: .
      dockerfile: Dockerfile.local
    command: [ "./run_local.sh" ]
    depends_on:
      - db
    env_file: .env_local
    ports: 
      - 8080:8080
    volumes:
      - ./src:/opt/app/src

volumes:
  db-data:
