version: '3.7'

services:

  postgres:
    environment:
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=sv_SE.UTF8"
    image: postgres:9.6-alpine
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data

  backend:
    build: .
    environment:
      POSTGRES_HOST: postgres
    ports: 
      - 8088:8080

volumes:
  db-data:
